/**
 * data.js — All portfolio content
 */

const PROJECTS = [
  {
    id:        "baja",
    num:       "PR-001",
    title:     "Olin Baja SAE · Project Manager",
    titleHtml: "Olin <em>Baja SAE</em>",
    cat:       "Vehicles",
    role:      "Project Manager · Drivetrain Lead",
    year:      "2024 — 2026",
    tools:     "Onshape · MATLAB · Mill / Lathe · Welding · Telemetry",
    tags:      ["Vehicles", "Controls", "Leadership", "Fabrication"],
    sum:       "Leading an 85‑student team designing, building, and racing a high‑performance off‑road vehicle. Rebuilt the organization, doubled team size, and stood up a 20‑sensor data pipeline.",
    lede:      "From suspension sub-team to Drivetrain Lead to Project Manager — the long arc of one program, told honestly.",
    heroLabel: "BAJA · PICTURE DAY 2025",
    heroImage: "../assets/baja-hero.jpg",
    featured:  true,
    feat:      true,
    kpis: [
      { k: "Team",    v: "85+ engineers" },
      { k: "Sensors", v: "20+ integrated" },
      { k: "Drive",   v: "Chain conversion" },
      { k: "Seasons", v: "3 design cycles" },
    ],
    body: [
      { h: "Context",        t: "The Baja SAE collegiate competition tasks student teams with designing and racing a single-seat off-road vehicle against a fixed ruleset. When I joined Olin Baja, we were roughly 40 people with a single car and a thin documentation trail.", img: "../assets/baja-02.jpg" },
      { h: "Leadership",     t: "As Project Manager I rebuilt the organizational foundation: sub-team charters, structured onboarding, a documentation culture, and a recruiting pipeline that took us to 85+ members without losing technical depth. Inclusion and mentorship are first-class metrics, not afterthoughts.", img: "../assets/baja-05.jpg" },
      { h: "Technical work", t: "I've shipped hardware across three sub-teams: suspension revisions, the prop-drive to chain-drive conversion, and the current data-acquisition architecture. 20+ sensors stream strain, suspension travel, driveline torque, and GPS back to a logger we designed in-house.", img: "../assets/baja-06.jpg" },
      { h: "Outcomes",       t: "Faster, more reliable car. More honest engineering decisions. A team that can onboard a sophomore and ship a production part with their name on it by spring.", img: "../assets/baja-07.jpg" },
    ],
    gallery: [
      "../assets/baja-hero.jpg",
      "../assets/baja-02.jpg",
      "../assets/baja-03.jpg",
      "../assets/baja-04.jpg",
      "../assets/baja-05.jpg",
      "../assets/baja-06.jpg",
      "../assets/baja-07.jpg",
      "../assets/baja-08.jpg",
      "../assets/baja-09.jpg",
      "../assets/baja-10.jpg",
      "../assets/baja-11.jpg",
      "../assets/baja-12.jpg",
      "../assets/baja-heic-IMG_9255.jpg",
      "../assets/baja-heic-IMG_9259.jpg",
      "../assets/baja-heic-IMG_9413.jpg",
      "../assets/baja-heic-IMG_9476.jpg",
      "../assets/baja-heic-IMG_6448.jpg",
      "../assets/baja-heic-IMG_6809.jpg",
      "../assets/baja-heic-IMG_8786.jpg",
      "../assets/baja-heic-IMG_9179.jpg",
      "../assets/baja-diagram.png",
    ],
  },
  {
    id:        "fpv",
    num:       "PR-003",
    title:     "FPV Drone · Custom Frame",
    titleHtml: "FPV <em>drone</em>",
    cat:       "Drones",
    role:      "Frame designer, builder, pilot",
    year:      "2023",
    tools:     "Onshape · Carbon fiber · Betaflight · F722 FC · 6S power",
    tags:      ["Drones", "CAD", "Flight"],
    sum:       "Self-designed racing drone frame (MK3) built from CNC-cut carbon fiber. Survived a 150-foot drop onto concrete. 5-mile range. 15% lighter than comparable off-the-shelf frames.",
    lede:      "One of my earliest top-to-bottom mechanical projects. Every mounting hole has a reason.",
    heroLabel: "DRONE · CLEAN BUILD",
    heroImage: "../assets/fpv-hero-new.jpg",
    featured:  true,
    feat:      false,
    kpis: [
      { k: "Frame",  v: "CNC carbon fiber" },
      { k: "Motors", v: "iFlight XING-E 2306 1800KV" },
      { k: "FC/ESC", v: "Mamba MK4 F722 / 55A" },
      { k: "Range",  v: "5 mi (env. dependent)" },
    ],
    body: [
      { h: "Why",           t: "One of my lifelong dreams was to feel what a bird feels. FPV drone racing was as close as I could get, and off-the-shelf frames all had compromises I didn't like — fitment issues, weak arms, and subpar video.", img: "../assets/fpv-hero.jpg" },
      { h: "MARC1 → MARC3", t: "Started with 3D-printed PLA (MARC1). Structural weaknesses and fitment problems forced a full redesign. MARC2 introduced CNC-cut high-ply carbon fiber with interlocking arm configurations, surviving a 150-foot drop onto concrete and cutting $50 off comparable market prices.", img: "../assets/fpv-01.jpg" },
      { h: "Specs",         t: "RunCam Racer Nano 2 (1000TVL, 145° FOV, <6ms latency). SpeedyBee TX800 VTX (25–800mW). CNHL 6S 1500mAh 100C battery. FrSky Taranis Q X7 controller with R-XSR receiver. Tuned in Betaflight against flight logs.", img: "../assets/fpv-02.jpg" },
      { h: "Build & tune",  t: "Hand-assembled and Betaflight-tuned against logs I pulled from my own flights. Crashes repaired. Key lesson: carbon is unforgiving, and soldering quality is the difference between a good flight and a fire.", img: "../assets/fpv-heic-IMG_0097.jpg" },
    ],
    gallery: [
      "../assets/fpv-cutout.png",
      "../assets/fpv-hero.jpg",
      "../assets/fpv-01.jpg",
      "../assets/fpv-02.jpg",
      "../assets/fpv-03.jpg",
      "../assets/fpv-04.png",
      "../assets/fpv-05.jpg",
      "../assets/fpv-06.jpg",
      "../assets/fpv-heic-IMG_0097.jpg",
      "../assets/fpv-heic-IMG_0098.jpg",
      "../assets/fpv-heic-IMG_0099.jpg",
      "../assets/fpv-heic-IMG_0101.jpg",
      "../assets/fpv-heic-IMG_0450.jpg",
      "../assets/fpv-heic-IMG_0510.jpg",
      "../assets/fpv-heic-IMG_0134.jpg",
    ],
  },
  {
    id:        "scribblz",
    num:       "PR-011",
    title:     "Scribblz · Wall-Climbing Robot",
    titleHtml: "Scribblz · <em>wall-climbing robot</em>",
    cat:       "Robotics / Mechatronics",
    role:      "Mechanical Lead · Impeller Design",
    year:      "2025",
    tools:     "Onshape · CFD · 3D Printing · Kiwi Drive · BLDC",
    tags:      ["Robotics", "Mechatronics", "Fluids", "CAD"],
    sum:       "Designed a vacuum-adhesion wall-climbing robot from scratch — custom impeller, evolving chassis, and compliant skirt system — achieving ~14,000 Pa suction on vertical glass.",
    lede:      "A wall-climbing robot that uses a custom high-RPM impeller to stick to vertical glass and maneuver with three-wheel holonomic drive.",
    heroLabel: "SCRIBBLZ · WALL-CLIMBING ROBOT",
    heroImage: "../assets/scribblz-real-rebuilt_sideview.jpg",
    featured:  true,
    feat:      false,
    kpis: [
      { k: "Suction",  v: "~14,000 Pa" },
      { k: "Impeller", v: "+366% airflow gain" },
      { k: "Weight",   v: "−110g chassis savings" },
      { k: "Drive",    v: "Kiwi 3-omni" },
      { k: "Role",     v: "Mechanical Lead" },
      { k: "Year",     v: "2024" },
    ],
    body: [
      {
        h: "The Challenge",
        t: "Scribblz is a wall-climbing robot designed to navigate vertical glass surfaces and apply UV-curable resin patterns. The core mechanical problem: generate enough suction force to hold the robot against gravity while keeping weight and form factor small enough to maneuver. We needed a system that could produce reliable vacuum adhesion with a single BLDC-driven impeller.",
        img: "../assets/scribblz-robot-overhead.png",
      },
      {
        h: "Impeller Design",
        t: "I iterated through five impeller geometries using hand calculations and CFD, starting from a straight-blade baseline and progressively tuning blade count, rake angle, and housing clearance. The final design — a 13-blade backward-curved impeller with a dedicated scroll housing — achieved approximately 14,000 Pa of static pressure and a 366% improvement in useful airflow over the v1 baseline. Tolerances on the blade tip gap were held to ±0.15 mm to minimize recirculation losses.",
        img: "../assets/scribblz-centrifugal-impeller.png",
      },
      {
        h: "Chassis Evolution",
        t: "The chassis went through three major design cycles. The first was a solid-printed monocoque that worked mechanically but was too heavy. The second was a ribbed lattice structure that saved mass but cracked at the motor mounts under vibrational loads. The third — a hybrid aluminum-insert + printed shell design — gave us the stiffness we needed at the mount points while shedding 110g off the second revision. All mounting geometry was designed for in-field impeller and wheel swaps without tools.",
        img: "../assets/scribblz-chassis-v3.png",
      },
      {
        h: "Skirt System",
        t: "The vacuum seal is formed by a compliant skirt that rides directly on the glass. Early rigid skirts leaked badly on any surface irregularity. The final design uses a layered straw-skirt approach — a stiffer inner ring for dimensional stability with a softer outer lip that conforms to surface variation. This system allows the robot to maintain suction even when traversing surface irregularities like window edges and framing.",
        img: "../assets/scribblz-straw-skirt.png",
      },
      {
        h: "Drive & Integration",
        t: "Three omnidirectional wheels arranged in a Kiwi drive configuration give the robot full holonomic mobility — it can translate in any direction and rotate in place without repositioning. The electronics bay houses the control stack, power distribution, and slip-ring for continuous rotation. A spool-based tether system manages power and data lines without tangling during maneuvers.",
        img: "../assets/scribblz-real-rebuilt_topview.jpg",
      },
    ],
    gallery: [
      "../assets/scribblz-real-rebuilt_sideview.jpg",
      "../assets/scribblz-real-rebuilt_topview.jpg",
      "../assets/scribblz-real-rebuilt_othersideview.jpg",
      "../assets/scribblz-real-rebuilt_bottomview.jpg",
      "../assets/scribblz-real-omniwheel_closeup.jpg",
      "../assets/scribblz-real-window.jpg",
      "../assets/scribblz-real-docking_station.jpg",
      "../assets/scribblz-real-breakage_bottomview.jpg",
      "../assets/scribblz-robot-overhead.png",
      "../assets/scribblz-centrifugal-impeller.png",
      "../assets/scribblz-fdm-impeller.png",
      "../assets/scribblz-resin-impeller.png",
      "../assets/scribblz-mixed-flow.png",
      "../assets/scribblz-propeller-test.png",
      "../assets/scribblz-chassis-v1.png",
      "../assets/scribblz-chassis-v3.png",
      "../assets/scribblz-straw-skirt.png",
      "../assets/scribblz-electronics-bay.png",
      "../assets/scribblz-slip-ring.png",
      "../assets/scribblz-spool-system.png",
      "../assets/scribblz-mount-cantilevered.png",
      "../assets/scribblz-mount-constrained.png",
      "../assets/scribblz-docking-guide.png",
      "../assets/scribblz-lidar-placement.png",
      "../assets/scribblz-lidar-target.png",
    ],
  },
  {
    id:        "cart",
    num:       "PR-002",
    title:     "Electric Golf Push Cart",
    titleHtml: "Electric golf <em>push cart</em>",
    cat:       "Mechanical Design",
    role:      "Sole designer, fabricator",
    year:      "2024",
    tools:     "SolidWorks · Aluminum tube · Brushless motor · Custom ESC · ESP32",
    tags:      ["Mechanical Design", "Embedded", "Product"],
    sum:       "A Wi‑Fi‑controlled motorized push cart with dual ESP32 microcontrollers, a custom 36:1 worm gearbox, and a pocket remote — built so my father could enjoy golf despite chronic back pain.",
    lede:      "A clean single-builder project: real hardware, real motor controller, real tolerance stack.",
    heroLabel: "CART · BUILD PHOTOS",
    heroImage: "../assets/cart-hero-new.jpg",
    featured:  true,
    feat:      false,
    kpis: [
      { k: "Drive",   v: "36:1 worm gearbox" },
      { k: "Control", v: "Wi-Fi · dual ESP32" },
      { k: "Remote",  v: "Pocket controller" },
      { k: "Parts",   v: "SLS carbon composite" },
    ],
    body: [
      { h: "Why",          t: "I wanted to enable my father — who has chronic back pain — to continue enjoying golf. Nothing on the market fit the bill at the right price, so I built one from scratch.", img: "../assets/cart-01.jpg" },
      { h: "Design",       t: "Custom 36:1 worm gearbox for hill-climbing torque. The frame evolved through multiple failed material iterations before settling on SLS carbon-composite parts for the critical structural members.", img: "../assets/cart-03.jpg" },
      { h: "Electronics",  t: "Dual ESP32 microcontrollers communicating over Wi-Fi — one in the cart, one in a pocket-sized remote. The wireless architecture means no trailing cable and full range across a fairway.", img: "../assets/cart-05.jpg" },
    ],
    gallery: [
      "../assets/cart-hero.jpg",
      "../assets/cart-01.jpg",
      "../assets/cart-02.jpg",
      "../assets/cart-03.jpg",
      "../assets/cart-04.jpg",
      "../assets/cart-05.jpg",
      "../assets/cart-06.jpg",
      "../assets/cart-07.jpg",
    ],
  },
  {
    id:        "tvc",
    num:       "PR-004",
    title:     "Thrust Vector Controlled Rocket",
    titleHtml: "TVC <em>rocket</em>",
    cat:       "Controls",
    role:      "Mechanical + controls",
    year:      "2023 — 2024",
    tools:     "Onshape · C++ · Arduino · MPU-6050 · Kalman · SG90 servos",
    tags:      ["Controls", "Embedded", "Aerospace"],
    sum:       "The VMAX Rocket — a model-scale thrust-vectoring rocket inspired by SpaceX's Raptor. Two-axis gimbal, Kalman-filtered IMU, PID controller at 100 Hz. Hardware complete, awaiting first launch.",
    lede:      "The project that taught me embedded controls aren't magic — they're just careful bookkeeping at high frequency.",
    heroLabel: "TVC · ROCKET ASSEMBLY",
    heroImage: "../assets/tvc-hero.jpg",
    featured:  true,
    feat:      false,
    kpis: [
      { k: "Loop",    v: "100 Hz PID" },
      { k: "Gimbal",  v: "2-axis, SG90 servos" },
      { k: "IMU",     v: "MPU-6050 (GY-521)" },
      { k: "Engine",  v: "Estes F15 · 44.4 N thrust" },
    ],
    body: [
      { h: "System",      t: "The VMAX Rocket bridges large-scale aerospace and model rocketry. A two-axis gimbaling motor mount replaces fins entirely — the mount pivots to direct thrust and keep the rocket on course, inspired by SpaceX's Raptor engine technology.", img: "../assets/tvc-01.jpg" },
      { h: "TVC mount",   t: "Fully modeled in Onshape and 3D-printed in high-grade PLA. Two SG90 servo motors tilt the engine based on real-time sensor data. The pivot point sits above the engine's thrust center, maximizing stability and efficiency.", img: "../assets/tvc-02.jpg" },
      { h: "Software",    t: "C++ flight code running on Arduino Uno (ATmega328P, 16 MHz). MPU-6050 provides 3-axis gyro and accelerometer data over I2C. A complementary filter feeds a Kalman estimator for attitude. PID output converts to servo PWM at 100 Hz. Integrator clamping prevents wind-up.", img: "../assets/tvc-06.jpg" },
      { h: "Challenges",  t: "Flexible PLA caused imbalanced thrust — upgraded to stiffer material. Over-filtering led to delayed responses — refined Kalman implementation. SD card write latency caused data bottlenecks — switched to high-speed card with optimized logging rates.", img: "../assets/tvc-07.jpg" },
      { h: "Next steps",  t: "MATLAB simulations to fine-tune PID gains. Goal: stable launch and recovery without parachutes. Future integration of advanced telemetry for real-time monitoring.", img: "../assets/tvc-05.png" },
    ],
    gallery: [
      "../assets/tvc-hero.jpg",
      "../assets/tvc-01.jpg",
      "../assets/tvc-02.jpg",
      "../assets/tvc-03.jpg",
      "../assets/tvc-04.jpg",
      "../assets/tvc-05.png",
      "../assets/tvc-06.jpg",
      "../assets/tvc-07.jpg",
      "../assets/tvc-08.jpg",
      "../assets/tvc-09.jpg",
      "../assets/tvc-10.jpg",
      "../assets/tvc-11.jpg",
      "../assets/tvc-12.jpg",
    ],
  },
  {
    id:        "cyclone",
    num:       "PR-008",
    title:     "Cyclone · 3 lb Battlebot",
    titleHtml: "Cyclone · <em>battlebot</em>",
    cat:       "Robotics",
    role:      "Designer, builder",
    year:      "2024",
    tools:     "SolidWorks · BLDC · ESC · TPU · 3S LiPo · Tank drive",
    tags:      ["Robotics", "Combat", "BLDC"],
    sum:       "A 3 lb featherweight BattleBot for NHRL competition. Vertical spinner at 16,500 RPM, tank drive, TPU + steel armor. Iterated from an unsteerable spinning disk to a precision combat robot.",
    lede:      "Designing to be hit at 16,500 RPM teaches you a lot about material science.",
    heroLabel: "CYCLONE · TOP VIEW",
    heroImage: "../assets/cyclone-hero-new.jpg",
    featured:  true,
    feat:      false,
    kpis: [
      { k: "Class",   v: "3 lb featherweight" },
      { k: "Weapon",  v: "Vertical spinner · 16,500 RPM" },
      { k: "Drive",   v: "Tank · brushed DC + planetary" },
      { k: "Power",   v: "3S LiPo" },
    ],
    body: [
      { h: "Concept",      t: "Built for the National Havoc Robot League (NHRL) during my junior year at Winchester High School. The original design was a spinning disk on wheels with no steering — focused purely on collision power, but completely uncontrollable.", img: "../assets/cyclone-01.jpg" },
      { h: "Iteration",    t: "Early prototypes explored a horizontal spinner inspired by Tombstone, but gyroscopic forces made the robot unstable. Carbon fiber-infused plastic couldn't withstand direct impacts from other spinning weapons. Both problems forced a full redesign.", img: "../assets/cyclone-02.jpg" },
      { h: "Final design", t: "Vertical spinner powered by a brushless motor and ESC at 16,500 RPM. Belt-driven weapon for efficient power transfer. Tank drive with independent brushed DC motors and planetary gearboxes for precise maneuvering. TPU wheels for traction and impact absorption. Steel top and bottom plates for armor.", img: "../assets/cyclone-05.jpg" },
      { h: "Testing",      t: "Weapon successfully shattered plywood panels and plastic test targets. TPU and steel layers absorbed multiple direct strikes without critical damage. Tank drive allowed precise maneuvering in combat simulations.", img: "../assets/cyclone-06.jpg" },
    ],
    gallery: [
      "../assets/cyclone-hero.png",
      "../assets/cyclone-01.jpg",
      "../assets/cyclone-02.jpg",
      "../assets/cyclone-03.png",
      "../assets/cyclone-04.jpg",
      "../assets/cyclone-05.jpg",
      "../assets/cyclone-06.jpg",
      "../assets/cyclone-07.jpg",
      "../assets/cyclone-08.jpg",
    ],
  },
  {
    id:        "barbell",
    num:       "PR-005",
    title:     "Barbell Clip",
    titleHtml: "Barbell <em>clip</em>",
    cat:       "Mechanical Design",
    role:      "Sole designer",
    year:      "2024 — 2025",
    tools:     "Onshape · Injection-mold DFM · TPU prototype · ABS",
    tags:      ["Mechanical Design", "DFM", "Product"],
    sum:       "A patent-pending barbell collar with a wedge mechanism that converts plate-impact forces into tighter grip — zero horizontal slippage during CrossFit drops. Designed for injection molding.",
    lede:      "A small, obsessive little mechanism. All the engineering lives in the wedge profile.",
    heroLabel: "CLIP · MK3 FRONT VIEW",
    heroImage: "../assets/barbell-hero-new.jpg",
    featured:  true,
    feat:      false,
    kpis: [
      { k: "Mechanism", v: "Patent-pending wedge" },
      { k: "Material",  v: "Cast ABS plastic" },
      { k: "Compat.",   v: "Standard 2\" Olympic bar" },
      { k: "Versions",  v: "3 design iterations" },
    ],
    body: [
      { h: "Problem",    t: "Traditional spring collars slide during CrossFit drops — the impact forces plates outward, pushing against the clip and causing dangerous weight shifts. Competition clips are expensive and slow. I wanted a collar that solved this mechanically.", img: "../assets/barbell-01.jpg" },
      { h: "MK1",       t: "Arms distributed the force loads, all replaceable without replacing the whole clip. Problem: the arms created leverage that actually pulled the clip away from the bar, worsening performance under load.", img: "../assets/barbell-03.png" },
      { h: "MK2",       t: "Replaced the arm design with a clasp and wedge mechanism using the plate's own hole geometry to create a wedging effect. Plate movement now increases the clip's grip on the barbell. Eliminated horizontal slippage.", img: "../assets/barbell-04.png" },
      { h: "MK3",       t: "Added high-friction rubber material to the grip surface, integrated the clasp into the clip body for seamless functionality, and incorporated a high-strength wedge design. Tested with CrossFit barbell cycling, Olympic lifts, heavy squats, and deadlifts.", img: "../assets/barbell-06.jpg" },
      { h: "Production", t: "Once the design and patent are finalized, the clip will be injection molded in cast ABS plastic for durability and performance at scale. Compatible with all Olympic barbells (2-inch) and all plate types.", img: "../assets/barbell-02.jpg" },
    ],
    gallery: [
      "../assets/barbell-hero.png",
      "../assets/barbell-01.jpg",
      "../assets/barbell-02.jpg",
      "../assets/barbell-03.png",
      "../assets/barbell-04.png",
      "../assets/barbell-05.png",
      "../assets/barbell-06.jpg",
      "../assets/barbell-07.jpg",
    ],
  },
  {
    id:        "hub",
    num:       "PR-006",
    title:     "Baja Wheel Hub",
    titleHtml: "Baja <em>wheel hub</em>",
    cat:       "CAD / Fabrication",
    role:      "Designer",
    year:      "2024 — 2025",
    tools:     "Onshape · FEA · CNC Milling · Lathe · 6061-T6 Al",
    tags:      ["CAD", "FEA", "Fabrication"],
    sum:       "A redesigned wheel hub for the Olin Baja SAE car — lighter, structurally optimized, and validated through FEA. Machined from 6061-T6 aluminum on a 3-axis Tormach CNC.",
    lede:      "Details-first mechanical design. Every gram and every fillet had to earn its place.",
    heroLabel: "HUB · MACHINED PART",
    heroImage: "../assets/hub-hero-new.jpg",
    featured:  true,
    feat:      false,
    kpis: [
      { k: "Material",    v: "6061-T6 Aluminum" },
      { k: "FEA · Jump",  v: "FOS 127.63" },
      { k: "FEA · Bump",  v: "FOS 35.17" },
      { k: "FEA · Tree",  v: "FOS 1.11" },
    ],
    body: [
      { h: "Scope",         t: "The wheel hub is the primary mounting point for the wheels and the critical power transfer link from the half shafts to the wheels. The redesign aimed to reduce weight, improve structural integrity, and maintain easy maintenance under racing conditions.", img: "../assets/hub-04.jpg" },
      { h: "Material",      t: "6061-T6 aluminum for its high strength-to-weight ratio and excellent corrosion resistance. Validated against measured torque-path loads from competition data.", img: "../assets/hub-hero-new.jpg" },
      { h: "Manufacturing", t: "CNC milling on a Tormach 3-axis for precise shaping; lathe operations for spline refinement. Design iterated through two major versions before reaching the final geometry.", img: "../assets/hub-01.png" },
      { h: "FEA results",   t: "Jump impact: FOS 127.63. Bump load: FOS 35.17. Tree collision (worst case): FOS 1.11 — the governing constraint that drove the final wall thickness. Validated at Olin Time Trials.", img: "../assets/hub-03.png" },
    ],
    gallery: [
      "../assets/hub-hero-new.jpg",
      "../assets/hub-01.png",
      "../assets/hub-02.png",
      "../assets/hub-03.png",
      "../assets/hub-04.jpg",
    ],
  },
  {
    id:        "burbles",
    num:       "PR-010",
    title:     "TheBurbles · Digital Agency",
    titleHtml: "TheBurbles · <em>digital agency</em>",
    cat:       "Entrepreneurship",
    role:      "Founder",
    year:      "2020 — 2025",
    tools:     "Ops · PPC · SEO · AI · Google Ads · Meta Ads",
    tags:      ["Entrepreneurship", "Ops"],
    sum:       "Digital marketing agency founded at 16, serving sports teams (Boston Glory, Portland Nitro) and small businesses. PPC campaigns outperform competitors by 50%+. Revenue, clients, and payroll from day one.",
    lede:      "My first real operating experience. Revenue, clients, and payroll at 16.",
    heroLabel: "AGENCY · BRAND MARK",
    heroImage: "../assets/burbles-hero-new.jpg",
    featured:  true,
    feat:      false,
    kpis: [
      { k: "Founded",   v: "2020" },
      { k: "PPC edge",  v: "50%+ above competitors" },
      { k: "Clients",   v: "Sports teams + SMBs" },
      { k: "Services",  v: "PPC · SEO · AI tooling" },
    ],
    body: [
      { h: "Origin",     t: "Founded TheBurbles in 2020, Winchester MA, fully remote. Specialized in pay-per-click advertising, SEO, and AI-driven marketing solutions. Served sports teams and small-to-medium businesses from the start.", img: "../assets/burbles-01.png" },
      { h: "What we do", t: "PPC campaigns on Google, Facebook, Instagram, and TikTok — helped sports teams boost attendance and ticket prices with up to 300% growth in a few months. SEO from keyword research to on-page optimization. AI-integrated tools for rapid campaign adjustment, predictive analytics, and automated reporting.", img: "../assets/burbles-05.jpg" },
      { h: "Clients",    t: "Boston Glory and Portland Nitro (AUDL professional ultimate frisbee teams), Unbrush hair products, and various small businesses. Each project delivered tailored strategies with measurable ROI.", img: "../assets/burbles-04.jpg" },
      { h: "Lessons",    t: "Running a real business at 16 taught me how to manage client relationships end-to-end — brief, spec, delivery, invoice. How to run a team. How to talk to non-engineers. How to ship on deadline when the client is waiting.", img: "../assets/burbles-02.jpg" },
    ],
    gallery: [
      "../assets/burbles-hero.png",
      "../assets/burbles-01.png",
      "../assets/burbles-02.jpg",
      "../assets/burbles-03.jpg",
      "../assets/burbles-04.jpg",
      "../assets/burbles-05.jpg",
      "../assets/burbles-06.jpg",
      "../assets/burbles-07.jpg",
      "../assets/burbles-08.jpg",
      "../assets/burbles-09.jpg",
      "../assets/burbles-10.jpg",
    ],
  },
  {
    id:        "dpa",
    num:       "PR-007",
    title:     "Digital Poker Assistant (DPA)",
    titleHtml: "Digital poker <em>assistant</em>",
    cat:       "Software for Hardware",
    role:      "Builder",
    year:      "2024",
    tools:     "React Native · Python · JavaScript · Roboflow · ML",
    tags:      ["Software", "CV", "Embedded"],
    sum:       "A mobile app that enhances in-person poker with ML chip counting from a phone camera, real-time hand probability, integrated bank payouts, and group leaderboards.",
    lede:      "Where computer vision meets card games. Latency matters more than you'd think.",
    heroLabel: "DPA · HOME SCREEN",
    heroImage: "../assets/dpa-hero.png",
    featured:  true,
    feat:      false,
    kpis: [
      { k: "Platform",  v: "iOS & Android" },
      { k: "Frontend",  v: "React Native" },
      { k: "ML",        v: "Object detection (Roboflow)" },
      { k: "Status",    v: "Launching on App Store" },
    ],
    body: [
      { h: "Problem",    t: "Managing poker games is tedious — manual chip counting, payout calculations, and tracking stats across sessions. Online apps solve the logistics but kill the social experience. DPA keeps the in-person game while automating the overhead.", img: "../assets/dpa-01.png" },
      { h: "Features",   t: "ML chip counting from a phone camera (object detection via Roboflow). Real-time hand probability calculations. Integrated virtual bank that logs buy-ins and auto-calculates payouts. Private rooms with invite system. Group stats and leaderboards across sessions.", img: "../assets/dpa-02.png" },
      { h: "Technology", t: "Frontend in React Native for seamless iOS and Android support. JavaScript for business logic. Python for camera-related ML tasks. Chip counting uses object detection and image classification. Hand probabilities employ advanced ML algorithms for real-time decision support.", img: "../assets/dpa-03.png" },
      { h: "Status",     t: "Coming soon to the App Store. The chip counting model is trained and validated; the bank and stats systems are complete. Hand probability integration is the final module before launch.", img: "../assets/dpa-04.png" },
    ],
    gallery: [
      "../assets/dpa-hero.png",
      "../assets/dpa-01.png",
      "../assets/dpa-02.png",
      "../assets/dpa-03.png",
      "../assets/dpa-04.png",
    ],
  },
  {
    id:        "stocks",
    num:       "PR-009",
    title:     "Stock Analysis · PCA + GBM",
    titleHtml: "Stock analysis <em>PCA + GBM</em>",
    cat:       "Software",
    role:      "Researcher",
    year:      "2025",
    tools:     "Python · scikit-learn · NumPy · Pandas",
    tags:      ["Software", "Research"],
    sum:       "Two-method stock prediction: candlestick PCA classifier (27% accuracy, outperforming random) and Geometric Brownian Motion on Amazon data (~95% directional accuracy). Results were humbling.",
    lede:      "Quantitative finance meets statistical modeling. The GBM result looked too good — that's the point.",
    heroLabel: "MODEL · OUTPUT CHART",
    heroImage: "../assets/stocks-hero.png",
    featured:  true,
    feat:      false,
    kpis: [
      { k: "Method 1",    v: "Candlestick PCA · 27% acc." },
      { k: "Method 2",    v: "GBM · ~95% directional" },
      { k: "Dataset",     v: "Amazon (AMZN)" },
      { k: "Language",    v: "Python · scikit-learn" },
    ],
    body: [
      { h: "Method 1 — PCA classifier", t: "Candlestick patterns classified using principal component analysis. Grayscale conversion and image resizing allowed pattern extraction. Achieved 27% accuracy — significantly outperforming random guessing at identifying bullish/bearish trends. Limitations: constant volatility assumptions, lossy preprocessing.", img: "../assets/stocks-hero.png" },
      { h: "Method 2 — GBM model",      t: "Geometric Brownian Motion applied to Amazon stock data. Balances long-term drift with short-term volatility to forecast price paths. Achieved ~95% directional accuracy. The result looks impressive but reflects GBM's alignment with the efficient market hypothesis — it's a strong null model, not a trading edge.", img: "../assets/stocks-01.png" },
      { h: "Takeaway",                  t: "Together, these methods provide actionable insight into what statistical structure exists in market data and what doesn't. The 27% PCA result is more honest than the 95% GBM result — knowing the difference is the lesson.", img: "../assets/stocks-02.png" },
    ],
    gallery: [
      "../assets/stocks-hero.png",
      "../assets/stocks-01.png",
      "../assets/stocks-02.png",
    ],
  },
];

/* ====================================================
   EXPERIENCE
==================================================== */
const EXPERIENCE = [
  {
    group: "Engineering · Leadership",
    items: [
      {
        when:    "2024 — NOW",
        role:    "Project Manager",
        org:     "Olin Baja SAE",
        loc:     "Needham, MA",
        cats:    ["engineering", "leadership"],
        rev:     "REV-C",
        desc:    "Lead an 85+ student engineering team designing, building, and racing a high-performance off-road vehicle. Own strategy, technical direction, recruiting, and competition readiness across six sub-teams.",
        bullets: [
          "Rebuilt the organizational foundation from the ground up — charters, onboarding, documentation.",
          "Doubled team size to 85+ members without losing technical depth.",
          "Stood up a data-driven engineering pipeline with 20+ integrated sensors (strain, travel, driveline, GPS).",
          "Fostered a culture of mentorship, inclusion, and ship-on-deadline.",
        ],
        stack: ["Leadership", "Systems", "Onshape", "Telemetry"],
      },
      {
        when:    "2023 — 2024",
        role:    "Drivetrain Lead",
        org:     "Olin Baja SAE",
        loc:     "Needham, MA",
        cats:    ["engineering", "leadership"],
        rev:     "REV-B",
        desc:    "Led the full conversion of the Baja car from prop-drive to chain-drive — owned sprocket and hub geometry, jackshaft layout, and torque-path validation through competition.",
        bullets: [
          "Sized chain, sprockets, and jackshaft against measured engine torque curves.",
          "Designed wheel hubs and axle interfaces; validated with FEA and instrumented runs.",
          "Took the conversion through a full design review, fabrication, and competition cycle.",
        ],
        stack: ["Drivetrain", "FEA", "Machining", "CAD"],
      },
      {
        when:    "2023",
        role:    "Suspension Engineer",
        org:     "Olin Baja SAE",
        loc:     "Needham, MA",
        cats:    ["engineering"],
        rev:     "REV-A",
        desc:    "Front A-arm revisions, shock mount analysis, and kinematics sweeps for camber and toe under full travel. My entry point onto the team — where I learned that a good part is one you can also actually make.",
        bullets: [
          "Camber/toe sweep across full suspension travel; documented the trade space.",
          "Shock mount redesign with a reduced stress concentration at the rod-end pocket.",
        ],
        stack: ["Kinematics", "Onshape", "FEA"],
      },
    ],
  },
  {
    group: "Industry · Internships",
    items: [
      {
        when:    "SUMMER 2025",
        role:    "Engineering Intern",
        org:     "Onshape by PTC",
        loc:     "Boston, MA",
        cats:    ["industry", "engineering"],
        rev:     "INT-01",
        desc:    "Worked inside the CAD platform I had already been using daily for four years. Shipped workflow improvements used by real customer teams in production.",
        bullets: [
          "Scoped, built, and shipped features against a customer-driven backlog.",
          "Bridged mechanical engineering intuition with platform development.",
          "Wrote documentation and internal demos that outlived the internship.",
        ],
        stack: ["JavaScript", "CAD", "Product"],
      },
      {
        when:    "2024",
        role:    "Technical Reviewer",
        org:     "Outlier",
        loc:     "Remote",
        cats:    ["industry"],
        rev:     "EVA-02",
        desc:    "Human-in-the-loop technical review and evaluation work for frontier AI models on engineering and reasoning tasks. Sharpened how I think about clear problem statements.",
        bullets: [
          "Authored and graded engineering reasoning prompts.",
          "Caught edge-cases in model outputs on multi-step mechanical problems.",
        ],
        stack: ["Evaluation", "Engineering Reasoning"],
      },
    ],
  },
  {
    group: "Entrepreneurship",
    items: [
      {
        when:    "2020 — NOW",
        role:    "Founder",
        org:     "TheBurbles · Digital Marketing Agency",
        loc:     "Winchester, MA",
        cats:    ["entrepreneurship", "leadership"],
        rev:     "FND-01",
        desc:    "Founded and scaled a digital marketing agency serving sports teams and small businesses. Specialized in PPC advertising and SEO, with an early and aggressive embrace of AI-driven tooling. Clients include Boston Glory, Portland Nitro, and Unbrush.",
        bullets: [
          "Operated client relationships end-to-end — brief, spec, delivery, invoice.",
          "PPC campaigns outperformed competitors by 50%+; drove up to 300% growth for sports team clients.",
          "Built content and ad systems on Google, Facebook, Instagram, and TikTok.",
          "Taught me how to run a team, ship on deadline, and talk to non-engineers.",
        ],
        stack: ["Operations", "PPC", "SEO", "AI Tools", "Leadership"],
      },
    ],
  },
  {
    group: "Education",
    items: [
      {
        when:    "2022 — 2026",
        role:    "B.S. Engineering",
        org:     "Franklin W. Olin College of Engineering",
        loc:     "Needham, MA",
        cats:    ["engineering"],
        rev:     "EDU-01",
        desc:    "A small, project-heavy engineering school where the coursework is a prototype and the textbook is a lab notebook. Concentration in mechanical systems, with coursework across controls, electronics, and design.",
        bullets: [
          "Coursework: Mechanics of Materials, Dynamics, Controls, Mechatronics, Principles of Engineering.",
          "Continuous project work across CAD, fabrication, embedded, and software.",
          "Languages: C++, Python, JavaScript, HTML, CSS, Java.",
        ],
        stack: ["Mechanical", "Controls", "Design", "C++", "Python"],
      },
    ],
  },
];

/* ====================================================
   HOBBIES
==================================================== */
const HOBBIES = [
  { t: "Golf",         em: "par plus a few",        d: "Home course regular. Bag, range, and a cart I built myself. The slow, quiet discipline of it balances out the shop.", meta: ["Handicap · in progress", "Since · 2014"] },
  { t: "Cars",         em: "and wrenches",           d: "Enthusiast-level turning of wrenches. Track days, maintenance, and the occasional honest weekend with a lift.",         meta: ["Daily · manual",          "Favorite · RWD"] },
  { t: "FPV flight",   em: null,                     d: "Freestyle and long-range quad flying. Soldering, tuning, crashing, repairing. Repeat.",                                meta: ["Sim · Liftoff",            "Goggles · DJI O3"] },
  { t: "Ski",          em: "east coast ice",         d: "New England ice, occasional powder days out west. Bindings set, edges sharp.",                                         meta: ["Days · 20+/yr",            "Since · childhood"] },
  { t: "Photography",  em: null,                     d: "Mostly shop and track, occasionally landscape. Manual everything, prime lenses, no stickers.",                         meta: ["Body · Fuji",              "Lens · 35 f/1.4"] },
  { t: "Reading",      em: "technical & otherwise",  d: "Technical deep-dives, engineering biographies, and the occasional novel to stay human.",                               meta: ["Now · Skunk Works",        "Next · Shoe Dog"] },
  { t: "Cooking",      em: null,                     d: "Sunday meals from scratch. Favorite kitchen tools are, predictably, the ones with tolerances.",                        meta: ["Go-to · pasta",            "Scale · grams"] },
  { t: "Hiking",       em: "with a notebook",        d: "Long days in the Whites. Notebook for observations, camera for the ones I can't draw fast enough.",                    meta: ["4000-footers · 12 / 48",   "Region · NH"] },
];
